language: scala
jdk:
  - oraclejdk8

stages:
  - name: test
  - name: release
    if: branch = travis-build-stages

jobs:
  include:
    - env: TEST="scalafmt"
      script: ./bin/scalafmt --test
    # - script: sbt languageserver/test
    - env: EVENT_TYPE=$TRAVIS_EVENT_TYPE
      script: echo $TRAVIS_EVENT_TYPE
    - env: TEST="tests.ctags"
      script: sbt *:scalametaEnableCompletions "metaserver/testOnly -- $TEST"
    - env: TEST="tests.search"
      script: sbt *:scalametaEnableCompletions "metaserver/testOnly -- $TEST"
    # - script: sbt *:scalametaEnableCompletions 'metaserver/testOnly -- tests.storage'
    # - script: sbt *:scalametaEnableCompletions 'metaserver/testOnly -- tests.FormatterTest'

    - stage: release
      # only if HEAD is a merge commit or a tag:
      script: >
        if [[ "$(git rev-list --merges HEAD^..HEAD)" || "$TRAVIS_TAG" ]]; then
            echo "release"
        else
            echo "push to master"
        fi

cache:
  directories:
    - $HOME/.sbt/0.13/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
    - $HOME/.coursier

before_cache:
- du -h -d 1 $HOME/.ivy2/cache
- du -h -d 2 $HOME/.sbt/
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
- rm -rf $HOME/.ivy2/local
